resources:
- name: QA-1.0.1001
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: flight-school2
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: DB2-Server-11.1.20123
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: Console-1.2
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: staging-app
  type: cf
  source:
    api: https://api.ng.bluemix.net
    username: ahilden@ca.ibm.com
    password: add44son
    organization: ahilden@ca.ibm.com
    space: dev


- name: dashDB-Snapshot-1.2.32.1
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master 

jobs:
  - name: test-app
    plan:
    - get: flight-school2
      trigger: true
    - get: Console-1.2
    - get: DB2-Server-11.1.20123
    - get: QA-1.0.1001
    - task: tests
      file: flight-school2/build.yml

  - name: deploy-to-bluemix
    serial: true
    plan:
      - aggregate:
          - get: flight-school2
            passed: [test-app]
            trigger: true
      - put: staging-app 
        params:
          manifest: flight-school2/manifest.yml

