resources:
- name: QA-1.0.1001
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: S55SnapShot-08142016 
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: DB2-Server-11.1.20123
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: Console-1.2
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: mpp-1.3
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: deploy-1.2
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: update-1.2
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: aws-1.2
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: security-1.2
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: monitoring-1.2
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: operations-1.2
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: softlayer-1.2
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master

- name: transactional-1.0.121
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master


- name: staging-app
  type: cf
  source:
    api: https://api.ng.bluemix.net
    username: ahilden@ca.ibm.com
    password: add44son
    organization: ahilden@ca.ibm.com
    space: dev





- name: dashDB-Snapshot-1.2.32.1
  type: git
  source:
    uri: https://github.com/ahilden/flight-school
    branch: master 

jobs:
  - name: DB2-Server-CVT
    plan:
    - get: DB2-Server-11.1.20123
  - name: Console-CVT
    plan:
    - get: Console-1.2
  - name: mpp-CVT
    plan:
    - get: mpp-1.3
  - name: deploy-CVT
    plan:
    - get: deploy-1.2
  - name: update-CVT
    plan:
    - get: update-1.2
  - name: aws-CVT
    plan:
    - get: aws-1.2
  - name: security-CVT
    plan:
    - get: security-1.2
  - name: monitoring-CVT
    plan:
    - get: monitoring-1.2
  - name: operations-CVT
    plan:
    - get: operations-1.2
  - name: transactional-CVT
    plan:
    - get: transactional-1.0.121
  - name: softlayer_CVT
    plan:
    - get: softlayer-1.2 
  - name: snapshot-build
    plan:
    - get: S55SnapShot-08142016 
      trigger: true
    - task: tests
      file: S55SnapShot-08142016/build.yml

  - name: basic-validation
    serial: true
    plan:
      - aggregate:
          - get: S55SnapShot-08142016
            passed: [snapshot-build]
            trigger: true
      - put: S55SnapShot-08142016
        params:
          manifest: S55SnapShot-08142016/manifest.yml

  - name: deploy-validation
    plan:
      - aggregate:
          - get: S55SnapShot-08142016
            passed: [basic-validation]
            trigger: true
      - put: S55SnapShot-08142016
        params:
          manifest: S55SnapShot-08142016/manifest.yml

  - name: update-validation
    plan:
      - aggregate:
          - get: S55SnapShot-08142016
            passed: [basic-validation]
            trigger: true

